In [60]:
import pandas as pd
import numpy as np
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

## Data Extraction and Initial Loading

In [61]:
# Set the path to the file you'd like to load
file_path = "sleep_deprivation_dataset_detailed.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "sacramentotechnology/sleep-deprivation-and-cognitive-performance",
  file_path,
)

print("First 5 records:", df.head())

First 5 records:   Participant_ID  Sleep_Hours  Sleep_Quality_Score  Daytime_Sleepiness  \
0             P1         5.25                   15                  12
1             P2         8.70                   12                  14
2             P3         7.39                   17                  10
3             P4         6.59                   14                   3
4             P5         3.94                   20                  12

   Stroop_Task_Reaction_Time  N_Back_Accuracy  Emotion_Regulation_Score  \
0                       1.60            64.20                        12
1                       2.54            65.27                        21
2                       3.40            74.28                        35
3                       3.54            72.42                        25
4                       3.09            99.72                        60

   PVT_Reaction_Time  Age  Gender    BMI  Caffeine_Intake  \
0             365.85   35  Female  30.53                2
1             288.95   20    Male  27.28                3
2             325.93   18    Male  30.00                1
3             276.86   18    Male  34.47                5
4             383.45   36    Male  29.70                3

   Physical_Activity_Level  Stress_Level
0                        1            33
1                        8            37
2                        2            32
3                        0            23
4                        4            14

In [62]:
# Create a copy of the DataFrame
df_copy = df.copy()

## Data Exploration and Initial Cleaning

In [64]:
# Display the first few rows of the dataset
df.head()

,Participant_ID,Sleep_Hours,Sleep_Quality_Score,Daytime_Sleepiness,Stroop_Task_Reaction_Time,N_Back_Accuracy,Emotion_Regulation_Score,PVT_Reaction_Time,Age,Gender,BMI,Caffeine_Intake,Physical_Activity_Level,Stress_Level
0,P1,5.25,15,12,1.60,64.20,12,365.85,35,Female,30.53,2,1,33
1,P2,8.70,12,14,2.54,65.27,21,288.95,20,Male,27.28,3,8,37
2,P3,7.39,17,10,3.40,74.28,35,325.93,18,Male,30.00,1,2,32
3,P4,6.59,14,3,3.54,72.42,25,276.86,18,Male,34.47,5,0,23
4,P5,3.94,20,12,3.09,99.72,60,383.45,36,Male,29.70,3,4,14

In [65]:
# Display the last few rows of the dataset
df.tail()

,Participant_ID,Sleep_Hours,Sleep_Quality_Score,Daytime_Sleepiness,Stroop_Task_Reaction_Time,N_Back_Accuracy,Emotion_Regulation_Score,PVT_Reaction_Time,Age,Gender,BMI,Caffeine_Intake,Physical_Activity_Level,Stress_Level
55,P56,8.53,16,16,3.51,64.76,41,391.48,34,Male,23.01,2,5,8
56,P57,3.53,19,16,3.24,66.13,36,355.01,24,Female,34.93,2,1,25
57,P58,4.18,3,1,2.62,92.43,29,397.13,41,Male,29.85,0,1,21
58,P59,3.27,4,1,4.32,56.83,33,330.70,40,Female,24.53,4,1,29
59,P60,4.95,6,21,4.42,85.45,21,419.01,22,Male,30.53,0,10,16

In [66]:
# Check the dimensions of the dataset
df.shape

(60, 14)

In [67]:
# Get column names and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Participant_ID             60 non-null     object
 1   Sleep_Hours                60 non-null     float64
 2   Sleep_Quality_Score        60 non-null     int64
 3   Daytime_Sleepiness         60 non-null     int64
 4   Stroop_Task_Reaction_Time  60 non-null     float64
 5   N_Back_Accuracy            60 non-null     float64
 6   Emotion_Regulation_Score   60 non-null     int64
 7   PVT_Reaction_Time          60 non-null     float64
 8   Age                        60 non-null     int64
 9   Gender                     60 non-null     object
 10  BMI                        60 non-null     float64
 11  Caffeine_Intake            60 non-null     int64
 12  Physical_Activity_Level    60 non-null     int64
 13  Stress_Level               60 non-null     int64
dtypes: float64(5), int64(7), object(2)
memory usage: 6.7+ KB

In [68]:
# Check for missing values
df.isnull().sum()

Participant_ID               0
Sleep_Hours                  0
Sleep_Quality_Score          0
Daytime_Sleepiness           0
Stroop_Task_Reaction_Time    0
N_Back_Accuracy              0
Emotion_Regulation_Score     0
PVT_Reaction_Time            0
Age                          0
Gender                       0
BMI                          0
Caffeine_Intake              0
Physical_Activity_Level      0
Stress_Level                 0
dtype: int64

In [69]:
# Generate descriptive statistics for numerical columns
df.describe()

,Sleep_Hours,Sleep_Quality_Score,Daytime_Sleepiness,Stroop_Task_Reaction_Time,N_Back_Accuracy,Emotion_Regulation_Score,PVT_Reaction_Time,Age,BMI,Caffeine_Intake,Physical_Activity_Level,Stress_Level
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.0000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,5.805500,8.316667,12.000000,3.245000,75.005833,38.1500,332.539000,29.516667,27.329333,2.383333,4.116667,17.866667
std,1.832357,5.637320,7.577845,0.827368,13.671457,17.1334,87.800288,8.168753,4.541382,1.688362,3.108717,11.015346
min,3.120000,0.000000,0.000000,1.600000,50.900000,10.0000,201.560000,18.000000,18.740000,0.000000,0.000000,0.000000
25%,4.107500,4.000000,6.000000,2.595000,64.620000,25.0000,257.535000,21.750000,23.580000,1.000000,1.000000,8.750000
50%,5.690000,8.000000,11.500000,3.260000,74.270000,37.0000,327.210000,28.500000,27.365000,2.500000,4.000000,17.500000
75%,7.285000,13.000000,19.000000,3.965000,85.600000,54.2500,402.845000,36.000000,30.747500,4.000000,6.000000,26.250000
max,8.820000,20.000000,24.000000,4.490000,99.730000,67.0000,494.550000,43.000000,34.930000,5.000000,10.000000,40.000000

In [70]:
# Check for duplicates in the dataset
df.duplicated().sum()

0

In [71]:
# Check the data types of all columns
df.dtypes

Participant_ID                object
Sleep_Hours                  float64
Sleep_Quality_Score            int64
Daytime_Sleepiness             int64
Stroop_Task_Reaction_Time    float64
N_Back_Accuracy              float64
Emotion_Regulation_Score       int64
PVT_Reaction_Time            float64
Age                            int64
Gender                        object
BMI                          float64
Caffeine_Intake                int64
Physical_Activity_Level        int64
Stress_Level                   int64
dtype: object

## Data Transformation and Feature Engineering